[project]
name = "skin-triage-model"
version = "0.1.0"
description = "Skin triage model package"
authors = [
    {name = "Clinikly"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "torch (>=2.7.0,<3.0.0)",
    "pillow (>=11.2.1,<12.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
